### ISSUE TITLE
Is Autolayout on save is intendent?

### ISSUE THREAD

**Issue by ivankhm** [statelyai/xstate-tools#135]
Hi, i have a question about the vscode extension.

Lets model an example:
1) I created a machine in ts file
2) opened visual editor for this machine
3) edited layout, moved nodes around, saved file
4) edited code in ts file - for example renamed event name, saved file

I expect:
- the layout says the same

What happens:
- the layout resets to Autolayout.

Dont get me wrong, the Autolayout is useful sometimes, but in my case it turns a visual board into unreadable a mess. 
Its gets better, if I model child states better, but still, it feels wierd.

**Is is behavior intendent? If yes, can it be avoided somehow?**

Thanks in advance!

**Comment by pct196** [comment]
Hi.

I'm also having problems with autolayout changing my layout.

Is it possible to add in a way to disable autolayout please?

Thank you,

Paul

**Comment by davidkpiano** [comment]
We will be fixing this soon - there is currently a PR for this internally.

**Comment by Andarist** [comment]
@ivankhm @pct196 could you recheck if this is still an issue for you?

**Comment by pct196** [comment]
Hi, @Andarist. No, this is fixed for me. I will let you folks know if I have any issues in the future. Thank you :)

**Comment by macasas** [comment]
I'm using xstate extension v2.0.0 almost 2 years after this issue was closed, and I am still getting automatic changes as soon as I type a single new character in the editor.  It isn't autolayout, because if I click that button I get a different, cleaner layout.

Each change in the text editor returns my visual editor to a mess.  
Click Autolayout, slightly less of a mess
Manually arrange, edit, lose all layout changes.
Sort of unusable, unless you like repeating the same manual layout changes over and over.
Did the problem come back just for me?


VSCode Version: 1.85.0
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:17:50.719Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 21.6.0

**Comment by benayala** [comment]
This is still an issue for me. v2.1.0
