### ISSUE TITLE
Visualizer pane keeps blinking

### ISSUE THREAD

**Issue by BasixKOR** [statelyai/xstate-tools#19]
![](https://media.discordapp.net/attachments/885197642357960764/895554715599908864/1.gif)

The visualizer pane keeps blinking even though nothing has changed.

**Comment by mdpratt** [comment]
I am not able to reproduce this issue with the latest version v1.5.14. Is is possible you had a linter or jest running in the background causing this?

**Comment by mattpocock** [comment]
@mdpratt I do still get this - it's a weakness with the way we render the visualiser. The fix for it would be:

1. Make a PR to xstate-viz to allow for changing the visualised machine via postMessage
2. Make the vscode extension communicate those messages

You would STILL get some blinking because of the way it's rendered. So then you'd need to:

3. Change the way the elk rendering works to ensure that the current machine is on screen while the other one is being pre-rendered.

**Comment by Andarist** [comment]
This is being improved in https://github.com/statelyai/xstate-tools/pull/232 . When it comes to the visualizer - we might still do a full refresh when you actually edit the displayed machine but we avoid refreshing when unrelated parts of the code change.
